
name: Deploy to Staging

on:
  push:
    branches:
      - develop  # Trigger on develop branch push

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd my-web-app  # Navigate to directory with Dockerfile
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest

    - name: SSH into EC2 and Deploy
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/WiseAnalytics/my-web-app  # ✅ Replace with actual path
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
          sudo docker-compose up -d  # ✅ Ensure docker-compose.yml is in this directory
        EOF
